import Head from 'next/head'
import Image from 'next/image'
import Layout from './components/Layout'
import profile from "../../public/Profile-Picture.png"

export default function Home() {
  return (
    <>
      <Head>
        <title>Website</title>
        <meta name='description' content='Generated by create next app' />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='flex items-center text-dark w-full min-h-screen'>
        <Layout className='pt-0'>
          <div className='flex items-center justify-between w-full'>
            <div className='w-1/2'>
              <Image src={profile} alt='Profile Picture' className='w-full h-auto' />
            </div>
          </div>
        </Layout>
      </main>
    </>

  )
}
